amazon-connect/amazon-connect-chat-ios

AmazonConnectChatIOSTests/Core/Network/WebSocketManagerTests.swift, Sources/Core/Network/AWSClient.swift, Sources/Core/Network/WebSocketManager.swift
*Issue #, if available:*
*Description of changes:*
Adding unit tests for core WebSocketManager functions
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Adding WebSocketManager unit tests

README.md, Sources/Core/Service/ChatSession.swift, Sources/Core/Utils/Logger/SDKLogger.swift, Sources/Core/Utils/Logger/SDKLoggerProtocol.swift
This PR implements SDKLogger overrides so that users can implement custom logging logic for SDK logs.
- Tested via iOS UI Example
* Disconnecting from chat
* Sending a message to the agent
* See typing bubbles on agent side
* See read/delivered receipt on client side
* Receiving a message from the agent
* See typing bubbles on client side
* See read/delivered receipt on agent side
* Sending an attachment to the agent (try .txt, .pdf, .jpg)
* Preview the attachment on click
* Receiving an attachment from the agent
* Preview the attachment on click
* Close the application (Without ending chat) → open app …
=> Implementing SDKLogger Overrides

README.md, Sources/PrivacyInfo.xcprivacy
- Updating privacy manifest file to correct format. No impact on code.
---
---
* Disconnecting from chat
* Sending a message to the agent
* See typing bubbles on agent side
* See read/delivered receipt on client …
=> Updated privacy manifest file

.github/workflows/Build.yml, AmazonConnectChatIOS.xcodeproj/project.pbxproj, AmazonConnectChatIOSTests/Core/Network/Mocks/MockWebSocketManager.swift, Package.swift, Sources/Core/Models/Event.swift, Sources/Core/Models/Message.swift, Sources/Core/Models/Metadata.swift, Sources/Core/Models/WebSocketErrorCodes.swift, Sources/Core/Network/WebSocketManager.swift, Sources/Core/Service/ChatService.swift, Sources/Core/Service/ChatSession.swift, Sources/Core/Utils/HttpClient/HttpHeader.swift
- The issue arises when users attempt to load the transcript from a previous session using persistent chat. While we were processing the response, we had added a “closing” WebSocket and sent a “chat has ended” callback to the customer after parsing an “chat ended” event that we received in the transcript. This fix prevents the action from being taken at the parsing level and instead sends the “chat has ended” callback to the customer once they disconnect and close the WebSocket simultaneously.
- Made Message/Event/Metadata initializers public #45 
- Included Chat disconnect event leak #42 
- Added `operation time out` to websocket connection retry. 
--- …
=> Previous session transcript fix , made initializer public

.github/workflows/semgrep.yaml, README.md, Sources/Core/Network/WebSocketManager.swift, Sources/Core/Service/ChatService.swift, Sources/Core/Service/ChatSession.swift
There are two WebSocket related changes in this PR
This PR implements and exposes two new functions, `suspendWebSocketConnection` and `resumeWebSocketConnection`.  Suspending websocket connections will disconnect the websocket and prevent any further attempts to re-establish a websocket connection.  The suspension can only be lifted by calling `resumeWebSocketConnection` which will immediately re-attempt to re-establish a connection to the active chat session.
This PR also implements background/foreground scenarios for websocket connectivity.  When backgrounded, the SDK will now preemptively disconnect the websocket and attempt to re-establish the connection when foregrounded.  This is a preventative measure since the OS …
=> [WebSocket]: Exposing suspend/resume methods + background/foreground logic

AmazonConnectChatIOSTests/Core/Network/Mocks/MockWebSocketManager.swift, AmazonConnectChatIOSTests/Core/Service/ChatServiceTests.swift, AmazonConnectChatIOSTests/Core/Service/MockChatService.swift, AmazonConnectChatIOSTests/Core/utils/MockConnectionDetailsProvider.swift, README.md, Sources/Core/Network/AWSClient.swift, Sources/Core/Network/MessageReceiptsManager.swift, Sources/Core/Service/ChatService.swift, Sources/Core/Service/ChatSession.swift, Sources/Core/Utils/CommonUtils.swift, Sources/Core/Utils/ConnectionDetailsProvider.swift
This PR introduces a new API: `ChatSession.reset`.  This API will remove all in-memory user session data such as internal transcript and tokens.  This will also disconnect the websocket connection.
This PR also adds a new user agent suffix configuration for the connect participant client. Here is an example UA string:
```
aws-sdk-iOS/2.40.1 iOS/18.1 en_US  AmazonConnect-Mobile Chat-iOS SDK/1.0.6
```
Note that the version will need to be updated manually in the `CommonUtils.swift` file each release.
---
*Does this change introduce backwards incompatible changes?* [YES/NO] NO
*Does this change introduce any new dependency?* [YES/NO]. NO
---
YES
*Have you tested the changes with a sample UI (e.g. …
=> Implementing ChatSession.reset API

Sources/Core/Models/ChatEvent.swift, Sources/Core/Network/WebSocketManager.swift, Sources/Core/Utils/CommonUtils.swift
* Fixing issue that message metadata is missing in getTranscript
* Adding interactiveResponse content type.
---
*Does this change introduce backwards incompatible changes?* [NO]
*Does this change introduce any new dependency?* [NO]
---
No
*Have you tested the changes with a sample UI?*
Yes
- started a chat a accepted from agent CCP
- sent messages from customer and read them from CCP, confirmed read receipts were displayed
- closed the app, then opened it again and reconnected to the existing chat to trigger a getTranscript, verified read receipts were still there
* Initiating chat and connecting …
=> Fixing issue that message metadata is missing in getTranscript

Sources/Core/Utils/CommonUtils.swift
There is an existing issue where if there is a message with a delivered receipt when we disconnect the chat, it will become a read receipt when we re-connect to the chat. This is because we check if it is read based on whether the read timestamp is a string, and even in the case where the read receipt is missing, we initialize it to an empty string.  This PR updates so that it is set to nil if it is not received.
We are also bumping the version to prepare for a release. 
---
NO
NO
---
NA
*Have you tested the changes with a sample UI (e.g. [iOS Mobile Chat …
=> Fixing metadata bug + updating version

Sources/Core/Network/AWSConnectParticipantAdapter.swift
This PR fixes an issue where we are incorrectly passing the result of the connect participant `sendEvent` response back to the `AWSClient` wrapper class.
We should be passing `task.result` instead of `task` which is causing the casting to `AWSConnectParticipantSendEventResponse` to fail in `AWSClient`.
---
NO
NO
---
NA
Here are a …
=> Fixing sendEvent

Sources/Core/Service/ChatService.swift
We are making two `getTranscript` calls whenever we re-connect to a chat session.  This is due to the additional `event == .connectionEstablished` check in `setupWebSocket`.
---
NO
NO
---
NA
YES
* Disconnecting …
=> Remove duplicate getTranscript call on reconnect

AmazonConnectChatIOSTests/Core/Network/Mocks/MockAWSClient.swift, AmazonConnectChatIOSTests/Core/Service/ChatServiceTests.swift, Sources/Core/Service/ChatService.swift
This PR fixes an unexpected `getTranscript` loop regarding the re-connection flow.  The issue stems from an unexpected behavior where calling `getTranscript` in the forward direction will always return the last item and a `nextToken` even if there are no more messages.
This PR fixes this issue by changing the conditional to add another check to see whether the last returned message is already within the internal transcript.  If it is, we already know that we have fetched all available messages.
---
NO
NO
---
YES
*Have you tested the changes with a sample UI (e.g. [iOS …
=> Fix getTranscript Loop on reconnection flow

AmazonConnectChatIOSTests/Core/Service/ChatServiceTests.swift, README.md, Sources/Core/Models/TranscriptItem.swift, Sources/Core/Service/ChatService.swift, Sources/Core/Service/ChatSession.swift, Sources/Core/Utils/CommonUtils.swift
This PR updates the `transcriptListPublisher` logic.
- Returns `TranscriptData` object which contains the original `transcriptList` property as well as a `previousTranscriptNextToken` string property.
- `previousTranscriptNextToken` represents the `nextToken` that will fetch the next batch of older transcripts
- Adding debounce to `transcriptListPublisher` updates to reduce the number of handler calls.  Original behavior would call the update event for each message in a `getTranscript` result (i.e. if `getTranscript` returned 100 messages, it would trigger 100 times).
---
YES
NO
---
*Is the code …
=> Updating transcriptListPublisher to pass back previousTranscriptNextToken

AmazonConnectChatIOS.podspec
Revert 'Prepare for release 3.3.3' committed by mistake - https://github.com/amazon-connect/amazon-connect-chat-ios/commit/0ac028e091f3f5d97339d9ab3bf620a9cf00a754
=> Revert 'Prepare for release 3.3.3' committed by mistake

.github/workflows/Build.yml
This PR fixes the `destination` that the tests run on.  Previously, it was set to iPhone 12 which was no longer supported as a testing device in GitHub Actions.  This uncovered a bug where the tests are not failing the CI step properly when a test fails.
This PR updates the `destination` to be an iPhone 15 build and improves logging of test failures and the logic within the step.
---
*Does this change introduce backwards incompatible changes?* [YES/NO]  NO
*Does this change introduce any new dependency?* [YES/NO]. NO
---
YES
*Have you tested the changes with a sample UI (e.g. [iOS Mobile Chat Example](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/mobileChatExamples/i …
=> Fixing and improving Build + Test CI Step

README.md
Fix README Formatting
README formatting is broken due to missing code block end syntax.
=> Fix README.md Formatting

Sources/Core/Service/ChatService.swift, Sources/Core/Utils/CommonUtils.swift
Chatsession.onEnded event was not firing previously. This adds delay so that the event is processed
---
*Does this change introduce backwards incompatible changes?* [YES]
*Does this change introduce any new dependency?* [YES]
---
*Is the code unit tested?* yes
*Have you tested the changes with a sample UI (e.g. [iOS Mobile Chat Example](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/mobileChatExamples/iOSChatExample))?* yes
End chat and see the event in onMessage, onTranscript and chatSession.onEnded
* Disconnecting from chat
* Sending a message to the agent
* See typing bubbles on agent …
=> fix chatsession.onChatEnded not firing

Sources/Core/Service/ChatService.swift, Sources/Core/Utils/TranscriptItemUtils.swift
- Use empty string timestamps for sending messages 
- Add special transcript insertion logic to ensure sending messages appear at end
- Update failed messages with current timestamp when failure occurs
- Add WebSocket message handling to replace placeholder timestamps with server timestamps
- Ensure proper chronological ordering while maintaining immediate UI feedback
Fixes issues where:
1. Message ordering could be disrupted during slow networks and different device times
---
*Does this change introduce backwards incompatible changes?* [No]
*Does this change introduce any new dependency?* [NO]
---
*Is the code unit tested?* Yes
https://github.com/user-attachments/assets/1b154855-5f60-471f-88ae-7baea37d074d …
=> Fix message timestamp display and ordering issues

Sources/Core/Service/ChatService.swift
Remove extra function to update timestamps, it is not needed and it impacts cases where the else branch was being taken
---
*Does this change introduce backwards incompatible changes?* [NO]
*Does this change introduce any new dependency?* [NO]
---
*Is the code unit tested?* yes
Test all basic functionality and set device time in the past
=> remove extra function

Sources/Core/Models/ConnectionDetails.swift, Sources/Core/Models/TranscriptItem.swift
We are making `TranscriptData` and `ConnectionDetails` initializers public to help consuming projects test more effectively.
---
NO
NO
---
NA
* Disconnecting from chat
* Sending a message to the agent
* See …
=> Add public initializers for TranscriptData and ConnectionDetails

Sources/Core/Utils/CommonUtils.swift
📦 Version Update:
- Updated getLibraryVersion() from 2.0.5 to 2.0.6
- Reflects latest SDK improvements and event callback features
🔧 Changes:
- CommonUtils.getLibraryVersion(): '2.0.5' → '2.0.6'
✅ This version includes:
- Comprehensive event callback system (10 new callbacks)
- Attachment status progression fixes
- Enhanced participant event handling
- Improved receipt callback functionality
- Connection state management improvements
Prepares SDK for 2.0.6 release with new event handling capabilities.
---
---
*Have you tested the changes with a sample UI (e.g. [iOS Mobile …
=> chore: update library version to 2.0.6
